name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x]

    steps:
    - name: Deploy 
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}

        script: | 
          cd ~
          dir=/root/portfolio
          if [ -d $dir] then
          then
           echo "Portfolio exists."
           cd portfolio
           git pull origin
           npm install
          else
          git clone https://github.com/abdulwahid211/portfolio.git
          cd portfolio
          npm install
          fi
          echo "Deployment successful to digital ocean"
